### ISSUE TITLE
client.subscribe : Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by jbruxelle** [unlocomqx/svelte-apollo-client#2] opened 2021-07-16 13:56 UTC
First, thanks for the fix on svelte-apollo (at least for queries). 💯 

However it does not seem to work with subscriptions (I first tried with my code, then with the given example from your repo, only replacing `.query(...)` with `.subscribe(...)`).

> Uncaught RangeError: Maximum call stack size exceeded
    at subscribe2 (subscribe.ts:11)
    at ApolloClient2.SvelteApolloClient.apolloClient.subscribe (client.ts:74)
    at subscribe2 (subscribe.ts:11)
    at ApolloClient2.SvelteApolloClient.apolloClient.subscribe (client.ts:74)
    at subscribe2 (subscribe.ts:11)

Seems like we have a loop here... [https://github.com/unlocomqx/svelte-apollo-client/blob/main/src/subscribe.ts](url).

I did not try mutation and restore yet, it might require a test.

**Comment by unlocomqx** [comment] 2021-07-16 14:17
Hi, are you using the latest version?
The unit tests pass successfully so this bug is part of a previous version probably

**Comment by jbruxelle** [comment] 2021-07-16 14:50
>"@sveltejs/kit": "^1.0.0-next.131"
"svelte": "^3.34.0",
    "svelte-check": "^2.0.0",
    "svelte-preprocess": "^4.0.0",

>"@apollo/client": "^3.3.21",
"graphql": "^15.5.1",
"svelte-apollo-client": "^0.1.0"

And the error also occurs when calling `.subscribe` from the repo example (after `yarn upgrade`).

**Comment by unlocomqx** [comment] 2021-07-16 15:07
It should be fixed in `0.1.2`

**Comment by jbruxelle** [comment] 2021-07-16 18:14
First, thanks for your reactivity !

However, it seems that storing apolloClient.subscribe in the _subscribe var has for result to unbind the apolloClient instance from the function.

> Cannot read property 'queryManager' of undefined
TypeError: Cannot read property 'queryManager' of undefined
    at ApolloClient.subscribe (D:\Documents\_WEB\Portfolio\frontend\node_modules\@apollo\client\core\core.cjs.js:1781:21)
    at ApolloClient.SvelteApolloClient.apolloClient.subscribe (D:\Documents\_WEB\Portfolio\frontend\node_modules\svelte-apollo-client\dist\svelte-apollo-client.cjs.js:146:26)
    at index.svelte:13:35
    at Object.$$render (D:\Documents\_WEB\Portfolio\frontend\node_modules\svelte\internal\index.js:1555:22)
    at Object.default (root.svelte:38:46)
    at eval (D:\Documents\_WEB\Portfolio\frontend\src\routes\__layout.svelte:20:36)
    at Object.$$render (D:\Documents\_WEB\Portfolio\frontend\node_modules\svelte\internal\index.js:1555:22)
    at root.svelte:36:44
    at $$render (D:\Documents\_WEB\Portfolio\frontend\node_modules\svelte\internal\index.js:1555:22)
    at Object.render (D:\Documents\_WEB\Portfolio\frontend\node_modules\svelte\internal\index.js:1563:26)

`this` is undefined in :
> ApolloClient.prototype.subscribe = function (options) {
        return this.queryManager.startGraphQLSubscription(options);
    };

Of course, trying `var _subscribe = apolloClient.subscribe.bind(apolloClient)` makes the loop thing happen again...

**Comment by unlocomqx** [comment] 2021-07-16 18:39
The problem is that I couldn't test it with a live subscription. My experience with graphql is quite limited.
Can you share code to test this with a public graphql API
For example, the spacex api offers public access to subscriptions
https://api.spacex.land/graphql/

**Comment by unlocomqx** [comment] 2021-07-16 18:57
If it's just simpler to use `client.sub` for example, then we can go with that

**Comment by jbruxelle** [comment] 2021-07-17 10:50
> The problem is that I couldn't test it with a live subscription. My experience with graphql is quite limited.
> Can you share code to test this with a public graphql API
> For example, the spacex api offers public access to subscriptions
> https://api.spacex.land/graphql/

My experience with graphql is quite limited too but after researches I have found something we can work with.
I couldn't use subscriptions with SpaceX API, but found another which works.

1. The API : https://graphql-compose.herokuapp.com/northwind/
2. The subscription code (in one tab) : 
> `subscription {
     orderCreated {
     shipName
  }
} `
3. A mutation code for what we are observing (in another tab)
> `mutation {
  createOrder(record:{ 
    shipName: "testOrderShipName"
  }) {
    error {
     message
  }
    record {
      shipName
  }
}}`

I will spend a little time searching for a solution today.

**Comment by unlocomqx** [comment] 2021-07-17 10:53
Thanks, I will use this one for testing and come up with a fix
Cheers

**Comment by unlocomqx** [comment] 2021-07-17 11:43
I created a test in the app folder, can you clone it and make a test?

<img width="355" alt="2021-07-17 at 12 42 PM" src="https://user-images.githubusercontent.com/793712/126035767-8055385b-2248-4a21-8eea-e71eb2b6e957.png">

I used `const _subscribe = (apolloClient as any).subscribe.bind(apolloClient);` and it just works


Cheers

**Comment by unlocomqx** [comment] 2021-07-17 12:19
Published `0.1.4` just now

**Comment by jbruxelle** [comment] 2021-07-17 13:36
And it works ! Good job, and thanks a lot.

**Closed as completed** 2021-07-17 13:36 UTC

**Comment by unlocomqx** [comment] 2021-07-17 13:38
That's great! 
Cheers
